=== Programming-Systems-Lab/archived-oracle/SemanticLookup.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.0 U (http://www.xmlspy.com) by Phil Gross (n/a) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="SemanticLookup">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Row" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Hint" type="xs:string"/>
							<xs:element name="SchemaURL" type="xs:anyURI"/>
							<xs:element name="TagProcessorURL" type="xs:anyURI"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Programming-Systems-Lab/archived-oracle/SemanticLookup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XML Spy v4.0 U (http://www.xmlspy.com)-->
<SemanticLookup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.cs.columbia.edu/~valetto/metaparser/SemanticLookup.xsd">
	<Row>
		<Hint>schema</Hint>
		<SchemaURL>http://www.cs.columbia.edu/~valetto/metaparser/schema.xsd</SchemaURL>
		<TagProcessorURL>http://www.cs.columbia.edu/~valetto/metaparser/tagprocessor.jar</TagProcessorURL>
	</Row>
	<Row>
		<Hint>schema2</Hint>
		<SchemaURL>http://www.cs.columbia.edu/~valetto/metaparser/schema2.xsd</SchemaURL>
		<TagProcessorURL>http://www.cs.columbia.edu/~valetto/metaparser/tagprocessor.jar</TagProcessorURL>
	</Row>
	<Row>
		<Hint>schema3</Hint>
		<SchemaURL>http://www.cs.columbia.edu/~valetto/metaparser/schema.xsd</SchemaURL>
		<TagProcessorURL>http://www.cs.columbia.edu/~valetto/metaparser/tagprocessor.jar</TagProcessorURL>
	</Row>
</SemanticLookup>
